/* Финансовый маркетплейс ВЭД: реальные игроки рынка.
   ⚠️ Условия (комиссии, сроки) носят СПРАВОЧНЫЙ характер по публичным данным
   на 2025–2026 и могут отличаться — перед сделкой уточняйте у провайдера.
   Источники: офиц. сайты компаний, публикации vc.ru / DTF / spark.ru, презентация V ALTER. */
window.AGENTS = [
  /* ===================== Платёжные агенты ВЭД ===================== */
  {
    id: "a7", type: "agent", name: "A7", color: "#E8472B",
    site: "a7.ru", plan: "Платёж день в день", verified: true, top: true,
    rating: 4.8, reviews: 540,
    commissionFrom: 0.3, commissionText: "от 0,3%",
    minAmount: 0, minText: "без минимума",
    termDays: 1, termText: "день в день",
    docDays: 1, docText: "в день платежа",
    countries: ["Китай", "ОАЭ", "Турция", "Япония", "Корея", "ЕС"],
    currencies: ["CNY", "USD", "EUR", "AED"],
    flow: ["import", "export"], deals: ["Товары", "Услуги", "Оборудование"],
    docs: "Контракт, инвойс, акт-отчёт", jurisdiction: "РФ · учреждён с ПАО «Банк ПСБ»",
    manager: true, currencyControl: true,
    limits: "Платёж в Китай за 4 часа", statusText: "Учреждён с ПАО ПСБ",
  },
  {
    id: "valter", type: "agent", name: "V ALTER", color: "#1B2A4A",
    site: "v-alter.ru", plan: "Подбор плательщика за 2 часа", verified: true, top: true,
    rating: 4.7, reviews: 210,
    commissionFrom: 0.8, commissionText: "от 0,8%",
    minAmount: 0, minText: "по запросу",
    termDays: 3, termText: "T+3",
    docDays: 1, docText: "T+1",
    countries: ["Китай", "Гонконг", "Турция", "ОАЭ", "Египет", "ЕС"],
    currencies: ["CNY", "USD", "EUR", "AED"],
    flow: ["import", "export"], deals: ["Товары", "Услуги", "Оборудование"],
    docs: "Контракт, инвойс, ВБК (УНК)", jurisdiction: "100+ компаний инфраструктуры по миру",
    manager: true, currencyControl: true,
    limits: "Любая валюта во все юрисдикции", statusText: "Проверен",
  },
  {
    id: "winwin", type: "agent", name: "Win Win Swift", color: "#0E7C5A",
    site: "winwin", plan: "Без скрытых сборов", verified: true, top: false,
    rating: 4.6, reviews: 178,
    commissionFrom: 0.5, commissionText: "от 0,5%",
    minAmount: 0, minText: "без минимума",
    termDays: 1, termText: "1 рабочий день",
    docDays: 1, docText: "акт + приложение",
    countries: ["Китай", "ЕС", "ОАЭ", "Турция", "СНГ"],
    currencies: ["USD", "EUR", "CNY", "AED"],
    flow: ["import", "export"], deals: ["Товары", "Услуги"],
    docs: "Акт, приложение к договору", jurisdiction: "Собственные каналы расчётов",
    manager: true, currencyControl: true,
    limits: "Юрлица и физлица", statusText: "Проверен",
  },
  {
    id: "gfved", type: "agent", name: "Global Finance VED", color: "#1F6FB2",
    site: "global-finance", plan: "Белый ВЭД · фикс. курс", verified: true, top: false,
    rating: 4.5, reviews: 96,
    commissionFrom: 0.9, commissionText: "от 0,9%",
    minAmount: 0, minText: "по запросу",
    termDays: 2, termText: "1–2 дня",
    docDays: 2, docText: "акт + отчёт",
    countries: ["Китай", "ЕС", "ОАЭ", "Турция"],
    currencies: ["USD", "EUR", "CNY"],
    flow: ["import", "export"], deals: ["Товары", "Контракты", "Услуги"],
    docs: "Контракт, инвойс, акт-отчёт", jurisdiction: "Лицензированные маршруты (SEPA / SWIFT-аналоги)",
    manager: true, currencyControl: true,
    limits: "Регулярные платежи", statusText: "Проверен",
  },
  {
    id: "rsi", type: "agent", name: "RSI Capital", color: "#6A2BD9",
    site: "rsi", plan: "Без валютного счёта", verified: true, top: false,
    rating: 4.4, reviews: 132,
    commissionFrom: 1.0, commissionText: "от 1,0%",
    minAmount: 0, minText: "без минимума",
    termDays: 2, termText: "1–2 дня",
    docDays: 2, docText: "ВЭД-отчётность",
    countries: ["Китай", "ОАЭ", "Турция", "СНГ", "ЕС"],
    currencies: ["USD", "EUR", "CNY", "AED", "RUB"],
    flow: ["import", "export"], deals: ["Товары", "Услуги"],
    docs: "Договор, инвойс", jurisdiction: "Мультивалютные расчёты",
    manager: true, currencyControl: true,
    limits: "1700+ операций в месяц · 24/7", statusText: "Проверен",
  },
  {
    id: "nnex", type: "agent", name: "NNEX", color: "#0F9D9D",
    site: "nnex", plan: "Онлайн-трекинг платежа", verified: false, top: false,
    rating: 4.3, reviews: 71,
    commissionFrom: 1.1, commissionText: "от 1,1%",
    minAmount: 0, minText: "по запросу",
    termDays: 2, termText: "1–3 дня",
    docDays: 2, docText: "акт + отчёт",
    countries: ["Китай", "ЕС", "Сингапур", "Гонконг"],
    currencies: ["USD", "EUR", "CNY"],
    flow: ["import"], deals: ["Товары", "Услуги"],
    docs: "Акт, отчёт", jurisdiction: "Международные платёжные хабы",
    manager: false, currencyControl: true,
    limits: "Статус транзакции онлайн", statusText: "На проверке",
  },

  /* ===================== Банки для ВЭД ===================== */
  {
    id: "psb", type: "bank", name: "ПСБ", color: "#F26822",
    site: "psbank.ru", plan: "Международные платежи + А7", verified: true, top: true,
    rating: 4.7, reviews: 980,
    commissionFrom: 0.3, commissionText: "от 0,3%",
    minAmount: 0, minText: "без минимума",
    termDays: 3, termText: "2–3 дня",
    docDays: 3, docText: "ВК банка",
    countries: ["Китай", "ОАЭ", "Турция", "Индия", "СНГ"],
    currencies: ["CNY", "USD", "EUR", "AED", "RUB"],
    flow: ["import", "export"], deals: ["Товары", "Услуги", "Оборудование"],
    docs: "Контракт, инвойс, паспорт сделки", jurisdiction: "РФ · лицензия ЦБ РФ",
    manager: true, currencyControl: true,
    limits: "Нужен расчётный счёт в ПСБ", statusText: "Лицензия ЦБ РФ",
  },
  {
    id: "tochka", type: "bank", name: "Точка Банк", color: "#7B2FF0",
    site: "tochka.com", plan: "РКО + платёжный агент ВЭД", verified: true, top: false,
    rating: 4.6, reviews: 1240,
    commissionFrom: 0.5, commissionText: "от 0,5%",
    minAmount: 0, minText: "без минимума",
    termDays: 2, termText: "1–3 дня",
    docDays: 2, docText: "ВК банка",
    countries: ["Китай", "ОАЭ", "Турция", "СНГ"],
    currencies: ["CNY", "USD", "EUR", "AED", "RUB"],
    flow: ["import", "export"], deals: ["Товары", "Услуги"],
    docs: "Контракт, инвойс", jurisdiction: "РФ · лицензия ЦБ РФ",
    manager: true, currencyControl: true,
    limits: "Для ИП и ООО", statusText: "Лицензия ЦБ РФ",
  },
  {
    id: "sovcom", type: "bank", name: "Совкомбанк", color: "#1E4FA3",
    site: "sovcombank.ru", plan: "ВЭД-сопровождение", verified: true, top: false,
    rating: 4.4, reviews: 610,
    commissionFrom: 0.6, commissionText: "от 0,6%",
    minAmount: 0, minText: "без минимума",
    termDays: 3, termText: "2–4 дня",
    docDays: 3, docText: "ВК банка",
    countries: ["Китай", "ОАЭ", "Турция", "Индия", "СНГ"],
    currencies: ["CNY", "USD", "EUR", "AED", "RUB"],
    flow: ["import", "export"], deals: ["Товары", "Услуги", "Оборудование"],
    docs: "Контракт, инвойс, паспорт сделки", jurisdiction: "РФ · лицензия ЦБ РФ",
    manager: true, currencyControl: true,
    limits: "Нужен расчётный счёт в банке", statusText: "Лицензия ЦБ РФ",
  },
];

/* Справочники для фильтров и формы */
window.DICT = {
  countries: ["Китай", "Гонконг", "ОАЭ", "Турция", "Египет", "Индия", "ЕС", "Сингапур", "Япония", "Корея", "СНГ"],
  currencies: ["CNY", "USD", "EUR", "AED", "RUB"],
};
